version: "3.8"

services:
  liberica21:
    build:
      context: .
      dockerfile: docker/bellsoft/Dockerfile
    container_name: liberica21
    ports:
      - "8080:8080"

  openjdk21:
    build:
      context: .
      dockerfile: docker/openjdk/21/Dockerfile
    container_name: openjdk21
    ports:
      - "8081:8080"

  temurin21:
    build:
      context: .
      dockerfile: docker/temurin/Dockerfile
    container_name: temurin21
    ports:
      - "8082:8080"

  graalvm21:
    build:
      context: .
      dockerfile: docker/graalvm/Dockerfile
    container_name: graalvm21
    ports:
      - "8083:8080"
