version: "3.8"

services:
  graalvm21:
    build:
      context: .
      dockerfile: docker/graalvm/Dockerfile
    container_name: graalvm21
    ports:
      - "8080:8080"

  openjdk21:
    build:
      context: .
      dockerfile: docker/openjdk/Dockerfile
    container_name: openjdk21
    ports:
      - "8081:8080"
